### ISSUE TITLE
support for polymorphic relations

### ISSUE THREAD

**Issue by ctf0** [laravie/query-filter#2]
is that possible ?

**Comment by crynobone** [comment]
Not at the moment but I will accept any Pull Request to add that feature.

**Comment by crynobone** [comment]
@ctf0 just merged the PR. But can you also add some tests to https://github.com/laravie/query-filter/blob/1.x/tests/Unit/Value/KeywordTest.php before I tagged a patch release.

**Comment by crynobone** [comment]
Will be part of 3.0.0 release.

**Comment by crynobone** [comment]
![CleanShot 2021-03-24 at 07 37 44](https://user-images.githubusercontent.com/172966/112238512-c217b180-8c7f-11eb-89b6-ec7e415efe94.png)

**Comment by ctf0** [comment]
v3 is not tagged yet.

**Comment by crynobone** [comment]
You should try it out and report any issue before we release as stable. 

Otherwise will have to wait for 4.0.0 to make any breaking changes.

**Comment by ctf0** [comment]
u dont need to worry about breaking changes when using major versions ex.`v2,v3,v4,etc..`

**Comment by ctf0** [comment]
**ps:**

the morph search is in the v2 readme, also `wildcardCharacter` is not documented.
