### ISSUE TITLE
search doesn't work if search term is not english

### ISSUE THREAD

**Issue by ctf0** [laravie/query-filter#3]
- Package Version: v1.6.1
- Laravel Version: 7.20.0
- PHP Version: PHP 7.4.7 (cli) (built: Jun 12 2020 00:00:24) ( NTS )
- Database Driver & Version: mysql v8.0.19 

### Description:
if search keyword is not english, the search query wont be applied

### Steps To Reproduce:
- add a some records with different english text and one record with a something else ex. in arabic `الجنة`
- try to search `new Searchable('الجنة', ['column_name']);`
- nothing will come out

**Comment by crynobone** [comment]
@ctf0 just merged the PR. But can you also add some tests to https://github.com/laravie/query-filter/blob/1.x/tests/Unit/Value/KeywordTest.php before I tagged a patch release.

**Comment by ctf0** [comment]
done
