### ISSUE TITLE
Column 'xxx' in where clause is ambiguous 

### ISSUE THREAD

**Issue by ctf0** [laravie/query-filter#6]
- Package Version: v1.6.2
- Laravel Version: 7.20.0
- PHP Version: PHP 7.4.7 (cli) (built: Jun 12 2020 00:00:24) ( NTS )
- Database Driver & Version: mysql v8.0.19 

### Description:
sometimes when searching in related relations we would get `Column 'xxx' in where clause is ambiguous `, the solution for it is to use 
```
$builder->qualifyColumn('column_name')
```
on each relation to make sure the column is scoped correctly to its table, but how/where to put that logic ?

### Steps To Reproduce:
it happens from time to time, on simple & complex relations.
- an example
```sql
SELECT
	*
FROM
	`accounts`
WHERE (EXISTS (
		SELECT
			*
		FROM
			`regions`
			INNER JOIN `clients` ON `clients`.`region_id` = `regions`.`id`
		WHERE
			`accounts`.`client_id` = `clients`.`id`
			and(`name` LIKE 'test'
				OR `name` LIKE 'test%'
				OR `name` LIKE '%test'
				OR `name` LIKE '%test%')
		ORDER BY
			`regions`.`created_at` DESC))
ORDER BY
	`accounts`.`created_at` DESC
```
- error
```
Query 1 ERROR: Column 'name' in where clause is ambiguous
```

**Comment by crynobone** [comment]
`$builder->qualifyColumn()` just bind the qualify name to current Model, it wouldn't work on all case why is why I doesn't include the usage.

**Comment by crynobone** [comment]
We need to first have good enough tests to ensure that the generated SQL is consistent to what we expect. 

Something like https://github.com/laravel/framework/blob/7.x/tests/Database/DatabaseEloquentBuilderTest.php#L754-L782

**Comment by ctf0** [comment]
we can take one step at a time, 
tell me what u think might be a fix for this, i will test it with all the cases that gave the error on my side and come back with concrete steps for the test, hows that sound ?

**Comment by crynobone** [comment]
What I responded need to come first.
